### PR TITLE
Remove Django version upper constraint

### LINKED ISSUE #1: Not compatible with Django 5.1.3
At https://github.com/pikhovkin/django-schema-viewer/blob/e0eec9abe28fe83b4dd1ff7950025d5efa966dc5/pyproject.toml#L49 is defined a constraint of being compatible only with Django 5.0.x, not with Django 5.1.0 or higher, so it's not possible to install the project with recent Django versions.

### PR DESCRIPTION
**Pull request by piranna**
Fix #1

### CODE REVIEW

**Comment by adamchainz** [comment]
Great. Indeed, upper version bounds are recommended against, per [this classic post](https://iscinumpy.dev/post/bound-version-constraints/#tldr).

**Comment by adamchainz** [comment]
@pikhovkin why do this? Please consider removing the upper bound to avoid blocking users in the future.

**Comment by pikhovkin** [comment]
> @pikhovkin why do this? Please consider removing the upper bound to avoid blocking users in the future.

it is done, check 0.4.2 version

**Comment by adamchainz** [comment]
Thank you, I see it was done in b5db7d3640861b41181008f2ec0ac05c8f8c5471

**Pull request closed without merging**
